/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Controller.Reports;
import javax.swing.JOptionPane;

/**
 *
 * @author AaronFM
 */
public class ReportViewer extends javax.swing.JFrame {

    private static ReportViewer rv;

    public static ReportViewer getInstance() {
        return rv == null ? (rv = new ReportViewer()) : rv;
    }

    private ReportViewer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnEx1 = new javax.swing.JButton();
        btnEx2 = new javax.swing.JButton();
        btnEx3 = new javax.swing.JButton();
        btnEx4 = new javax.swing.JButton();
        btnEx5 = new javax.swing.JButton();
        btnEx6 = new javax.swing.JButton();
        btnEx7 = new javax.swing.JButton();
        lblCustom = new javax.swing.JLabel();
        lblPreset = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UD3.PRACTICA1 - AaronFM");
        setName(""); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnEx1.setText("Ex1");
        btnEx1.setMaximumSize(new java.awt.Dimension(60, 25));
        btnEx1.setMinimumSize(new java.awt.Dimension(60, 25));
        btnEx1.setName(""); // NOI18N
        btnEx1.setPreferredSize(new java.awt.Dimension(60, 25));
        btnEx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnEx1, gridBagConstraints);

        btnEx2.setText("Ex2");
        btnEx2.setMaximumSize(new java.awt.Dimension(60, 25));
        btnEx2.setMinimumSize(new java.awt.Dimension(60, 25));
        btnEx2.setName(""); // NOI18N
        btnEx2.setPreferredSize(new java.awt.Dimension(60, 25));
        btnEx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnEx2, gridBagConstraints);

        btnEx3.setText("Ex3");
        btnEx3.setMaximumSize(new java.awt.Dimension(60, 25));
        btnEx3.setMinimumSize(new java.awt.Dimension(60, 25));
        btnEx3.setName(""); // NOI18N
        btnEx3.setPreferredSize(new java.awt.Dimension(60, 25));
        btnEx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnEx3, gridBagConstraints);

        btnEx4.setText("Ex4");
        btnEx4.setMaximumSize(new java.awt.Dimension(60, 25));
        btnEx4.setMinimumSize(new java.awt.Dimension(60, 25));
        btnEx4.setName(""); // NOI18N
        btnEx4.setPreferredSize(new java.awt.Dimension(60, 25));
        btnEx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnEx4, gridBagConstraints);

        btnEx5.setText("Ex5");
        btnEx5.setMaximumSize(new java.awt.Dimension(60, 25));
        btnEx5.setMinimumSize(new java.awt.Dimension(60, 25));
        btnEx5.setName(""); // NOI18N
        btnEx5.setPreferredSize(new java.awt.Dimension(60, 25));
        btnEx5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnEx5, gridBagConstraints);

        btnEx6.setText("Ex6");
        btnEx6.setMaximumSize(new java.awt.Dimension(60, 25));
        btnEx6.setMinimumSize(new java.awt.Dimension(60, 25));
        btnEx6.setName(""); // NOI18N
        btnEx6.setPreferredSize(new java.awt.Dimension(60, 25));
        btnEx6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnEx6, gridBagConstraints);

        btnEx7.setText("Ex7");
        btnEx7.setMaximumSize(new java.awt.Dimension(60, 25));
        btnEx7.setMinimumSize(new java.awt.Dimension(60, 25));
        btnEx7.setName(""); // NOI18N
        btnEx7.setPreferredSize(new java.awt.Dimension(60, 25));
        btnEx7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnEx7, gridBagConstraints);

        lblCustom.setText("Personalizados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(lblCustom, gridBagConstraints);

        lblPreset.setText("Predefinidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(lblPreset, gridBagConstraints);

        setSize(new java.awt.Dimension(337, 196));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * EJERCICIO 1 Informe predefinido.
     *
     * Mostrará: DNI, nombre, ap1, ap2 y edad de todos los registros.
     */
    private void btnEx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx1ActionPerformed
        Reports.predefinedFullReport();
    }//GEN-LAST:event_btnEx1ActionPerformed

    private void btnEx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx2ActionPerformed
        Reports.predefinedUnderagedReport();
    }//GEN-LAST:event_btnEx2ActionPerformed

    private void btnEx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx3ActionPerformed
        Reports.predefinedAgeDistributedReport();
    }//GEN-LAST:event_btnEx3ActionPerformed

    private void btnEx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx4ActionPerformed
        String dni = JOptionPane.showInputDialog("Introduce el DNI a buscar:");
        Reports.customFullReport(dni);
    }//GEN-LAST:event_btnEx4ActionPerformed

    private void btnEx5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx5ActionPerformed
        MinMaxAge.getInstance(this).setVisible(true);
    }//GEN-LAST:event_btnEx5ActionPerformed

    private void btnEx6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx6ActionPerformed

    }//GEN-LAST:event_btnEx6ActionPerformed

    private void btnEx7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx7ActionPerformed

    }//GEN-LAST:event_btnEx7ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEx1;
    private javax.swing.JButton btnEx2;
    private javax.swing.JButton btnEx3;
    private javax.swing.JButton btnEx4;
    private javax.swing.JButton btnEx5;
    private javax.swing.JButton btnEx6;
    private javax.swing.JButton btnEx7;
    private javax.swing.JLabel lblCustom;
    private javax.swing.JLabel lblPreset;
    // End of variables declaration//GEN-END:variables
}
